config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  scope '(:locale)', locale: /#{I18n.config.available_locales.join('|')}/ do
    devise_for :users
    root 'page#home'

    get 'login' => 'page#login'
    post 'login', to: 'page#check_user'
    get 'register', to: 'page#register'
    post 'add_user', to: 'page#add_user'
    get 'forgot', to: 'page#forgot'
    get 'password', to: 'page#password'
    get 'email_sent', to: 'page#email_sent'

    # resources :posts

    # devise_for :users, controllers: { sessions: 'users/sessions' }
    devise_scope :user do
      get 'page/sign_in', to: 'devise/sessions#new'
    end

    # Articles
    resources :articles do
      member do
        get 'filter'
      end
    end

    # Categories
    get 'categories' => 'categories#index'
    get 'categories/new' => 'categories#new'
    post 'categories/add' => 'categories#add'
    get 'categories/:id' => 'categories#show', as: 'categories_show'
    get 'categories/:id/edit' => 'categories#edit', as: 'categories_edit'
    patch 'categories/:id/update' => 'categories#update', as: 'categories_update'
    delete 'categories/:id/delete' => 'categories#delete', as: 'categories_delete'

    # Subcategories
    get 'subcategories' => 'subcategories#index'
    get 'subcategories/new' => 'subcategories#new'
    post 'subcategories/add' => 'subcategories#add'
    get 'subcategories/:id' => 'subcategories#show', as: 'subcategories_show'
    get 'subcategories/:id/edit' => 'subcategories#edit', as: 'subcategories_edit'
    patch 'subcategories/:id/update' => 'subcategories#update', as: 'subcategories_update'
    delete 'subcategories/:id/delete' => 'subcategories#delete', as: 'subcategories_delete'

    get 'home', to: 'page#home'
  end
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category
  delegate :title, to: :category, prefix: true
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  def index
    @subcategories = Subcategory.all.order(id: :desc)
  end

  def new
    @categories = Category.all
  end

  def add
    @subcategory = Subcategory.new(form_params)

    if(@subcategory.save())
      redirect_to subcategories_show_path(@subcategory.id)
    else
      render('new')
    end
  end

  def edit
    @categories = Category.all
    begin
      @subcategory = Subcategory.find(params[:id])
    rescue
      @subcategory = false
    end
  end

  def update
    @subcategory = Subcategory.find(params[:id])

    if(@subcategory.update(form_params))
      redirect_to subcategories_show_path(@subcategory.id)
    else
      render('edit')
    end
  end

  def show
    begin
      @subcategory = Subcategory.find(params[:id])
    rescue
      @subcategory = false
    end
  end

  def delete
    @subcategory = Subcategory.find(params[:id])
    @subcategory.destroy

    redirect_to subcategories_path
  end

  private
  def form_params
    params.require(:add_subcategory_form).permit(:category_id, :title, :desc)
  end
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/subcategories/edit.html.erb
<h2>Edit subcategory</h2>
<div class="form-wrap">
  <% if(@subcategory) %>
    <% if @subcategory.errors.any? %>
      <% @subcategory.errors.full_messages.each do |error| %>
        <div class="alert alert-danger"><%= error %></div>
      <% end %>
    <% end %>
    <%= form_for :add_subcategory_form, url: subcategories_update_path(@subcategory.id), method: :patch do |f| %>
      <%= f.label :title %>
      <%= f.text_field(:title, {:class => 'form-control', :value => @subcategory.title}) %>
      <br>
      <%= f.label :desc %>
      <%= f.text_area(:desc, {:class => 'form-control', :value => @subcategory.desc}) %>
      <br>
      <br>
      <%= f.label :category_id %>
      <%= f.select(:category_id, options_from_collection_for_select(@categories, 'id', 'title', @subcategory.category_id), {}, {:class => 'form-control'}) %>
      <br>
      <%= link_to 'Add Category', categories_new_path %>
      <br>
      <br>
      <%= f.submit('Save subcategory', {:class => 'btn btn-success'}) %>
    <% end %>
  <% else %>
    <h2>Category with such id not found</h2>
  <% end %>
  <br>
  <%= link_to 'Back to Subcategories', subcategories_path %>
</div>

app/views/subcategories/index.html.erb
<div class="articles">
  <%= link_to '+ New Subcategory', subcategories_new_path, {:class => 'add-btn'} %>
  <h2>Subcategories</h2>
  <% if(@subcategories.any?) %>
    <% @subcategories.each do |subcategory| %>
      <div class="article">
        <div class="btn-group">
          <span class="material-icons dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">more_horiz</span>
          <div class="dropdown-menu">
            <%= link_to 'Edit', subcategories_edit_path(subcategory.id), {:class => 'dropdown-item'} %>
            <%= link_to 'Delete', subcategories_delete_path(subcategory.id), {:class => 'dropdown-item', method: :delete} %>
          </div>
        </div>
        <div>
          <div class="title"><%= subcategory.title %></div>
          <div class="desc"><%= subcategory.desc %></div>
          <div class="desc">Category: <%= subcategory.category_title %></div>
        </div>
      </div>
    <% end %>
  <% else %>
    There are no subcategories
  <% end %>
</div>

app/views/subcategories/new.html.erb
<h2>Add new Subcategory</h2>
<% if @subcategory && @subcategory.errors.any? %>
  <% @subcategory.errors.full_messages.each do |error| %>
    <div class="alert alert-danger"><%= error %></div>
  <% end %>
<% end %>
<%= form_for :add_subcategory_form, url: subcategories_add_path do |f| %>
  <%= f.label :title %>
  <%= f.text_field(:title, {:class => 'form-control'}) %>
  <br>
  <%= f.label :desc %>
  <%= f.text_area(:desc, {:class => 'form-control'}) %>
  <br>
  <%= f.label :category_id %>
  <%= f.select(:category_id, options_from_collection_for_select(@categories, 'id', 'title'), {}, {:class => 'form-control'}) %>
  <br>
  <%= link_to 'Add Category', categories_new_path %>
  <br>
  <br>
  <%= f.submit('Save subcategory', {:class => 'btn btn-success'}) %>
<% end %>
<br>
<%= link_to 'Back to Subcategories', subcategories_path %>

app/views/subcategories/show.html.erb
<div class="show-article">
  <% if(@subcategory) %>
    <h2>Current subcategory</h2>
    <div>Title: <%= @subcategory.title %></div>
    <div>Description: <%= @subcategory.desc %></div>
    <div>Category: <%= @subcategory.category_title %></div>
    <hr>
    <%= link_to 'Edit', subcategories_edit_path(@subcategory) %>
    <br>
    <%= link_to 'Delete', subcategories_delete_path(@subcategory), method: :delete %>
  <% else %>
    <h2>Subcategory with such id not found</h2>
  <% end %>
  <hr>
  <%= link_to 'Back to subcategories', subcategories_path %>
</div>