config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  scope '(:locale)', locale: /#{I18n.config.available_locales.join('|')}/ do
    devise_for :users
    root 'page#home'

    get 'login' => 'page#login'
    post 'login', to: 'page#check_user'
    get 'register', to: 'page#register'
    post 'add_user', to: 'page#add_user'
    get 'forgot', to: 'page#forgot'
    get 'password', to: 'page#password'
    get 'email_sent', to: 'page#email_sent'

    # resources :posts

    # devise_for :users, controllers: { sessions: 'users/sessions' }
    devise_scope :user do
      get 'page/sign_in', to: 'devise/sessions#new'
    end

    # Articles
    resources :articles do
      member do
        get 'filter'
      end
    end

    # Categories
    get 'categories' => 'categories#index'
    get 'categories/new' => 'categories#new'
    post 'categories/add' => 'categories#add'
    get 'categories/:id' => 'categories#show', as: 'categories_show'
    get 'categories/:id/edit' => 'categories#edit', as: 'categories_edit'
    patch 'categories/:id/update' => 'categories#update', as: 'categories_update'
    delete 'categories/:id/delete' => 'categories#delete', as: 'categories_delete'

    # Subcategories
    get 'subcategories' => 'subcategories#index'
    get 'subcategories/new' => 'subcategories#new'
    post 'subcategories/add' => 'subcategories#add'
    get 'subcategories/:id' => 'subcategories#show', as: 'subcategories_show'
    get 'subcategories/:id/edit' => 'subcategories#edit', as: 'subcategories_edit'
    patch 'subcategories/:id/update' => 'subcategories#update', as: 'subcategories_update'
    delete 'subcategories/:id/delete' => 'subcategories#delete', as: 'subcategories_delete'

    get 'home', to: 'page#home'
  end
end

app/views/page/email_sent.html.erb
<div class="login">
  <div class="row">
    <div class="col-sm-5">
      <div class="left-side">
        <div class="home-link">
          <%= link_to 'Sports Hub', home_url %>
        </div>
        <div class="img-wrap">
          <%= image_tag('/assets/login.png') %>
        </div>
      </div>
    </div>
    <div class="col-sm-7">
      <div class="right-side">
        <div class="register-wrap">
          <%= link_to 'Don’t have an account?', new_user_registration_path, class: 'register' %>
          <%= link_to 'Get Started', new_user_registration_path, class: 'get-started' %>
        </div>
        <div class="form">
          <div class="email-sent">
            <span class="material-icons">mail_outline</span>
          </div>
          <div class="form-label text-center">Check your email jonhdoe@gmail.com</div>
          <div class="form-label3 text-center">If there's Sports Hub account linked to this email address, we'll send over instructions to reset your password.</div>
          <div class="back">
            <%= link_to 'Back to Log In', new_user_session_path  %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/page/forgot.html.erb
<div class="login">
  <div class="row">
    <div class="col-sm-5">
      <div class="left-side">
        <div class="home-link">
          <%= link_to 'Sports Hub', home_url %>
        </div>
        <div class="img-wrap">
          <%= image_tag('/assets/login.png') %>
        </div>
      </div>
    </div>
    <div class="col-sm-7">
      <div class="right-side">
        <div class="register-wrap">
          <%= link_to 'Don’t have an account?', new_user_registration_path, class: 'register' %>
          <%= link_to 'Get Started', new_user_registration_path, class: 'get-started' %>
        </div>
        <div class="form">
          <div class="form-label">Forgot your password?</div>
          <div class="form-label3">Enter your email address below and we’ll get you back on track.</div>
          <%= form_for :login_form, url: '/login' do |f| %>
            <%= f.label :email, 'Email address' %>
            <%= f.email_field :email, placeholder: 'Email@gmail.com' %>
            <%= f.submit 'Request reset link' %>
          <% end %>
          <div class="back">
            <%= link_to 'Back to Log In', new_user_session_path  %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/page/home.html.erb
<div class="top-block">
  <div class="img-wrap">
    <%= image_tag('/assets/home.png') %>
    <% if (@articles) %>
      <div class="side-article-wrap">
        <% @articles.each_with_index do |article, index| %>
          <div class="side-article <%= index == 0 ? 'active' : '' %>" id="article_<%= article.id %>">
            <div class="art-wrap">
              <div class="publish-date">
                <%= t 'published' %> / <%= l article.published_at, format: :long %>
              </div>
              <div class="title">
                <%= article.title %>
              </div>
              <div class="desc">
                <%= article.desc[0..80] %>
                <% if(article.desc.length > 80) %>
                  ...
                <% end %>
              </div>
            </div>
            <div class="block-btn">
              <%= link_to t('more'), article_path(article.id) %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="pagination" id="pagination">
        <span class="material-icons arrow-left">chevron_left</span>
        <% @articles.each_with_index do |article, index| %>
          <span class="page <%= index == 0 ? 'active' : '' %>" data-id="<%= article.id %>"><%=index+1 %></span>
        <% end %>
        <span class="material-icons arrow-right">chevron_right</span>
      </div>
    <% end %>
  </div>
</div>
<div class="news-block">
  <% @articles.each_with_index do |article, index| %>
    <div class="new">
      <% if(article.image) %>
        <div class="img-wrap"><%= image_tag('/uploads/' + article.image) %></div>
      <% end %>
      <div class="title"><%= article.title %></div>
      <div class="desc"><%= article.desc %></div>
      <a href="<%= article_path(article.id) %>" class="more">
        <span class="material-icons">east</span>
      </a>
    </div>
  <% end %>
</div>
<div class="separator">
  <div class="center"><%= t '.breakdown' %></div>
</div>
<div class="news-2">
  <div class="img-wrap">
    <%= image_tag('/assets/field.png') %>
  </div>
  <div class="title">Lorem ipsum dolor sit amet, consectetur</div>
</div>

app/views/page/login.html.erb
<div class="login">
  <div class="row">
    <div class="col-sm-5">
      <div class="left-side">
        <div class="home-link">
          <%= link_to 'Sports Hub', home_url %>
        </div>
        <div class="img-wrap">
          <%= image_tag('/assets/login.png') %>
        </div>
      </div>
    </div>
    <div class="col-sm-7">
      <div class="right-side">
        <div class="register-wrap">
          <%= link_to 'Don’t have an account?', new_user_registration_path, class: 'register' %>
          <%= link_to 'Get Started', new_user_registration_path, class: 'get-started' %>
        </div>
        <div class="form">
          <div class="form-label">Log in to Sports Hub</div>
          <div class="socials">
            <div class="facebook">
              <a href="#">
                <%= image_tag('/assets/fb.png') %>
              </a>
            </div>
            <div class="google">
              <a href="#">
                <%= image_tag('/assets/fb.png') %>
              </a>
            </div>
          </div>
          <% if @user && @user.errors.any? %>
            <% @user.errors.full_messages.each do |error| %>
              <div class="alert alert-danger"><%= error %></div>
            <% end %>
          <% end %>
          <%= form_for :login_form, url: '/login' do |f| %>
            <%= f.label :email %>
            <%= f.email_field :email %>
            <%= link_to 'Forgot password', forgot_path, class: 'forgot-password' %>
            <%= f.label :password %>
            <%= f.password_field :password %>
            <%= f.submit 'LOG IN' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/page/password.html.erb
<div class="login">
  <div class="row">
    <div class="col-sm-5">
      <div class="left-side">
        <div class="home-link">
          <%= link_to 'Sports Hub', home_url %>
        </div>
        <div class="img-wrap">
          <%= image_tag('/assets/login.png') %>
        </div>
      </div>
    </div>
    <div class="col-sm-7">
      <div class="right-side">
        <div class="register-wrap">
          <%= link_to 'Don’t have an account?', new_user_registration_path, class: 'register' %>
          <%= link_to 'Get Started', new_user_registration_path, class: 'get-started' %>
        </div>
        <div class="form">
          <div class="form-label">Please enter your new password.</div>
          <%= form_for :login_form, url: '/login' do |f| %>
            <%= f.label :new_password %>
            <%= f.password_field :new_password %>
            <%= f.label :password %>
            <%= f.password_field :password %>
            <%= f.submit 'set new password' %>
          <% end %>
          <div class="back">
            <%= link_to 'Back to Log In', new_user_session_path  %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/page/register.html.erb
<div class="login">
  <div class="row">
    <div class="col-sm-5">
      <div class="left-side">
        <div class="home-link">
          <%= link_to 'Sports Hub', home_url %>
        </div>
        <div class="img-wrap">
          <%= image_tag('/assets/login.png') %>
        </div>
      </div>
    </div>
    <div class="col-sm-7">
      <div class="right-side">
        <div class="register-wrap">
          <%= link_to 'Already have an account?', new_user_session_path, class: 'register' %>
          <%= link_to 'Log in', new_user_session_path, class: 'get-started' %>
        </div>
        <div class="form">
          <div class="form-label">Create Account</div>
          <div class="socials">
            <div class="facebook">
              <a href="#">
                <%= image_tag('/assets/fb.png') %>
              </a>
            </div>
            <div class="google">
              <a href="#">
                <%= image_tag('/assets/fb.png') %>
              </a>
            </div>
          </div>
          <div class="form-label2">OR use your email for registration:</div>
          <%= form_for :register_form, url: add_user_path do |f| %>
            <% if @user && @user.errors.any? %>
              <% @user.errors.full_messages.each do |error| %>
                <div class="alert alert-danger"><%= error %></div>
              <% end %>
            <% end %>
            <div class="row">
              <div class="col-sm-6">
                <%= f.label :firstname, 'First name' %>
                <%= f.text_field :firstname, placeholder: 'John' %>
              </div>
              <div class="col-sm-6">
                <%= f.label :lastname, 'Last name' %>
                <%= f.text_field :lastname, placeholder: 'Doe' %>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-12">
                <%= f.label :email %>
                <%= f.email_field :email, placeholder: 'jonhdoe@gmail.com' %>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-12">
                <%= f.label :password, 'Password' %>
                <%= f.password_field :password, placeholder: '8 + characters (letters and numbers)' %>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-12">
                <%= f.label :password_confirmation, 'Password Confirm' %>
                <%= f.password_field :password_confirmation %>
              </div>
            </div>
            <%= f.submit 'SIGN UP' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>