config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  scope '(:locale)', locale: /#{I18n.config.available_locales.join('|')}/ do
    devise_for :users
    root 'page#home'

    get 'login' => 'page#login'
    post 'login', to: 'page#check_user'
    get 'register', to: 'page#register'
    post 'add_user', to: 'page#add_user'
    get 'forgot', to: 'page#forgot'
    get 'password', to: 'page#password'
    get 'email_sent', to: 'page#email_sent'

    # resources :posts

    # devise_for :users, controllers: { sessions: 'users/sessions' }
    devise_scope :user do
      get 'page/sign_in', to: 'devise/sessions#new'
    end

    # Articles
    resources :articles do
      member do
        get 'filter'
      end
    end

    # Categories
    get 'categories' => 'categories#index'
    get 'categories/new' => 'categories#new'
    post 'categories/add' => 'categories#add'
    get 'categories/:id' => 'categories#show', as: 'categories_show'
    get 'categories/:id/edit' => 'categories#edit', as: 'categories_edit'
    patch 'categories/:id/update' => 'categories#update', as: 'categories_update'
    delete 'categories/:id/delete' => 'categories#delete', as: 'categories_delete'

    # Subcategories
    get 'subcategories' => 'subcategories#index'
    get 'subcategories/new' => 'subcategories#new'
    post 'subcategories/add' => 'subcategories#add'
    get 'subcategories/:id' => 'subcategories#show', as: 'subcategories_show'
    get 'subcategories/:id/edit' => 'subcategories#edit', as: 'subcategories_edit'
    patch 'subcategories/:id/update' => 'subcategories#update', as: 'subcategories_update'
    delete 'subcategories/:id/delete' => 'subcategories#delete', as: 'subcategories_delete'

    get 'home', to: 'page#home'
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true, length: {minimum: 4}
  validates :desc, presence: true, length: {minimum: 4}

  has_many :subcategories, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all.order(id: :desc)
  end

  def new
  end

  def add
    @category = Category.new(form_params)

    if(@category.save())
      redirect_to categories_show_path(@category.id)
    else
      render('new')
    end
  end

  def edit
    begin
      @category = Category.find(params[:id])
    rescue
      @category = false
    end
  end

  def update
    @category = Category.find(params[:id])

    if(@category.update(form_params))
      redirect_to categories_show_path(@category.id)
    else
      render('edit')
    end
  end

  def show
    begin
      @category = Category.find(params[:id])
    rescue
      @category = false
    end
  end

  def delete
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path
  end

  private
  def form_params
    params.require(:add_category_form).permit(:title, :desc)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<h2>Edit category</h2>
<div class="form-wrap">
  <% if(@category) %>
    <% if @category.errors.any? %>
      <% @category.errors.full_messages.each do |error| %>
        <div class="alert alert-danger"><%= error %></div>
      <% end %>
    <% end %>
    <%= form_for :add_category_form, url: categories_update_path(@category.id), method: :patch do |f| %>
      <%= f.label :title %>
      <%= f.text_field(:title, {:class => 'form-control', :value => @category.title}) %>
      <br>
      <%= f.label :desc %>
      <%= f.text_area(:desc, {:class => 'form-control', :value => @category.desc}) %>
      <br>
      <%= f.submit('Save category', {:class => 'btn btn-success'}) %>
    <% end %>
  <% else %>
    <h2>Category with such id not found</h2>
  <% end %>
  <br>
  <%= link_to 'Back to Categories', categories_path %>
</div>

app/views/categories/index.html.erb
<div class="articles">
  <%= link_to '+ New Category', categories_new_path, {:class => 'add-btn'} %>
  <h2>Categories</h2>
  <% if(@categories.any?) %>
    <% @categories.each do |category| %>
      <div class="article">
        <div class="btn-group">
          <span class="material-icons dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">more_horiz</span>
          <div class="dropdown-menu">
            <%= link_to 'Edit', categories_edit_path(category.id), {:class => 'dropdown-item'} %>
            <%= link_to 'Delete', categories_delete_path(category.id), {:class => 'dropdown-item', method: :delete} %>
          </div>
        </div>
        <div>
          <div class="title"><%= category.title %></div>
          <div class="desc"><%= category.desc %></div>
        </div>
      </div>
    <% end %>
  <% else %>
    There is no categories
  <% end %>
</div>

app/views/categories/new.html.erb
<h2>Add new Category</h2>
<% if @category && @category.errors.any? %>
  <% @category.errors.full_messages.each do |error| %>
    <div class="alert alert-danger"><%= error %></div>
  <% end %>
<% end %>
<%= form_for :add_category_form, url: categories_add_path do |f| %>
  <%= f.label :title %>
  <%= f.text_field(:title, {:class => 'form-control'}) %>
  <br>
  <%= f.label :desc %>
  <%= f.text_area(:desc, {:class => 'form-control'}) %>
  <br>
  <%= f.submit('Save category', {:class => 'btn btn-success'}) %>
<% end %>
<br>
<%= link_to 'Back to Categories', categories_path %>

app/views/categories/show.html.erb
<div class="show-article">
  <% if(@category) %>
    <h2>Current category</h2>
    <div>Title: <%= @category.title %></div>
    <div>Description: <%= @category.desc %></div>
    <hr>
    <%= link_to 'Edit', categories_edit_path(@category) %>
    <br>
    <%= link_to 'Delete', categories_delete_path(@category), method: :delete %>
  <% else %>
    <h2>Category with such id not found</h2>
  <% end %>
  <hr>
  <%= link_to 'Back to categories', categories_path %>
</div>