config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  scope '(:locale)', locale: /#{I18n.config.available_locales.join('|')}/ do
    devise_for :users
    root 'page#home'

    get 'login' => 'page#login'
    post 'login', to: 'page#check_user'
    get 'register', to: 'page#register'
    post 'add_user', to: 'page#add_user'
    get 'forgot', to: 'page#forgot'
    get 'password', to: 'page#password'
    get 'email_sent', to: 'page#email_sent'

    # resources :posts

    # devise_for :users, controllers: { sessions: 'users/sessions' }
    devise_scope :user do
      get 'page/sign_in', to: 'devise/sessions#new'
    end

    # Articles
    resources :articles do
      member do
        get 'filter'
      end
    end

    # Categories
    get 'categories' => 'categories#index'
    get 'categories/new' => 'categories#new'
    post 'categories/add' => 'categories#add'
    get 'categories/:id' => 'categories#show', as: 'categories_show'
    get 'categories/:id/edit' => 'categories#edit', as: 'categories_edit'
    patch 'categories/:id/update' => 'categories#update', as: 'categories_update'
    delete 'categories/:id/delete' => 'categories#delete', as: 'categories_delete'

    # Subcategories
    get 'subcategories' => 'subcategories#index'
    get 'subcategories/new' => 'subcategories#new'
    post 'subcategories/add' => 'subcategories#add'
    get 'subcategories/:id' => 'subcategories#show', as: 'subcategories_show'
    get 'subcategories/:id/edit' => 'subcategories#edit', as: 'subcategories_edit'
    patch 'subcategories/:id/update' => 'subcategories#update', as: 'subcategories_update'
    delete 'subcategories/:id/delete' => 'subcategories#delete', as: 'subcategories_delete'

    get 'home', to: 'page#home'
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="copyright">
    <div class="text">Copyright ©2019 <%= t('sport_hub') %></div>
    <div class="text"><%= t('privacy') + ' / ' +  t('terms') %></div>
  </div>
  <div class="logo">
    <%= link_to t('sport_hub'), home_url %>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <row>
    <div class="top-menu">
      <div class="logo">
        <%= link_to t('sport_hub'), home_url %>
      </div>
      <span class="search">
        <span class="material-icons">search</span>
        <input type="text" placeholder="<%= t 'search' %>">
      </span>
      <span class="socials">
        <span class="social-label"><%= t 'share' %></span>
        <a href="#">
          <%= image_tag('/assets/facebook.svg') %>
        </a>
        <a href="#">
          <%= image_tag('/assets/twitter.svg') %>
        </a>
        <a href="#">
          <%= image_tag('/assets/google.svg') %>
        </a>
      </span>
      <span class="profile">
        <span class="image">
            <%= image_tag('/assets/profile.svg') %>
        </span>
        <span class="username">
          <a href="<%= destroy_user_session_path %>" data-method="delete">Ivan Baloh</a>
        </span>
        <span class="material-icons">arrow_drop_down</span>
      </span>
      <span class="lang-wrap">

      <div class="btn-group">
        <span class="lang"><%= I18n.locale %></span>
        <span class="material-icons dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">arrow_drop_down</span>
        <div class="dropdown-menu">
          <% I18n.config.available_locales.each do |locale| %>
            <%= link_to locale, root_path(locale: locale) + request.path.from(3), {:class => 'dropdown-item'} %>
          <% end %>
        </div>
      </div>
      </span>
    </div>
  </row>
</header>

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
  <ul>
    <li class="<%=current_page?(home_url) ? 'active' : '' %>">
      <%= link_to t('home'), home_url %>
    </li>
    <li><a href="#"><%= t 'sidebar.nba' %></a></li>
    <li><a href="#"><%= t 'sidebar.nfl' %></a></li>
    <li><a href="#">MLB</a></li>
    <li><a href="#"><%= t 'sidebar.nhl' %></a></li>
    <li><a href="#">CBB</a></li>
    <li><a href="#">CFB</a></li>
    <li><a href="#"><%= t 'sidebar.nascar' %></a></li>
    <li><a href="#"><%= t 'sidebar.golf' %></a></li>
    <li><a href="#"><%= t 'sidebar.soccer' %></a></li>
    <li><a href="#"><%= t 'sidebar.team_hub' %></a></li>
    <li class="<%=current_page?(articles_path) ? 'active' : '' %>"><%= link_to t('articles'), articles_path %></li>
    <li class="<%=current_page?(categories_path) ? 'active' : '' %>"><%= link_to t('categories'), categories_path %></li>
    <li class="<%=current_page?(subcategories_path) ? 'active' : '' %>"><%= link_to t('subcategories'), subcategories_path %></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SportApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons' %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js' %>
    <%= javascript_include_tag 'https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if (notice) %>
      <div class="alert alert-success"><%= notice %></div>
    <% end %>
    <% if (alert) %>
      <div class="alert"><%= alert %></div>
    <% end %>

    <% if (user_signed_in?) %>
      <%= render '/layouts/header' %>
      <div class="content">
        <div class="row">
          <div class="col-sm-2">
            <%= render '/layouts/sidebar' %>
          </div>
          <div class="col-sm-10">
            <%= yield %>
          </div>
        </div>
      </div>
      <%= render '/layouts/footer' %>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>